name: tubes_android
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  shared_preferences: ^2.5.1
  image_picker: ^1.1.2
  file_picker: ^9.0.0
  open_file: ^3.5.10
  image_picker_web: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # assets:
  # - images/restoran.jpeg
